### ISSUE TITLE
Rename repository and artifacts to zeebe-spring-boot

### ISSUE THREAD

**Issue by menski** [zeebe-io/spring-zeebe#18]
I would suggest to rename the project and artifacts to zeebe-spring-boot, this would better match with other Zeebe projects. What do you think?

**Comment by jangalinski** [comment]
well, boot is not correct, since the core implementation works without spring boot, boot-starters are convient helpers, but you will be able to work with regular spring as well.

Naming was borrowed from spring-amqp which uses the same annotation-style subscriptions, so its a well known naming pattern for spring developers. 

But I would be fine with zeebe-spring if it is a better fit.

**Comment by menski** [comment]
Okay thanks for the inside. I'm not so familiar with the spring world. So I'm fine with choosing which matches best in the spring eco system. And if that is `spring-zeebe` than we should keep it that way.
