### ISSUE TITLE
spring-zeebe-starter is not using the configuration from application.yml

### ISSUE THREAD

**Issue by vvalencia-cl** [zeebe-io/spring-zeebe#49]
I think there is a problem with spring-zeebe-starter, as it's not working as intended.

It isn't using the configured properties declared in application.yml that maps to io.zeebe.spring.client.properties.ZeebeClientConfigurationProperties.
I think it's just using the defaults configured in: io.zeebe.spring.client.config.ZeebeClientSpringConfiguration#DEFAULT

How to reproduce this problem:

If you start the example (io.zeebe.spring.example.StarterApplication) without having an instance of zeebe's broker running, you'll see this error:

```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /0.0.0.0:26500
```

If you change the port in the example's configuration:

```
zeebe:
  broker:
    contactPoint: "localhost:26700"
```

The error keeps showing the default value:

```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /0.0.0.0:26500
```

Looking in the structure of ZeebeClientConfigurationProperties, the configuration should be:

```
zeebe:
  client:
    broker:
      contactPoint: "localhost:26700"
```

But that produces the same wrong result as before.

The problem seems to be that the AutoConfiguration (io.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration) is doing nothing with
the ConfigurationProperties (io.zeebe.spring.client.properties.ZeebeClientConfigurationProperties)

Am I not understanding or using in a bad way the spring-zeebe-starter or there is a problem with the dependency?

Also, I think there is a problem/discrepancy with the worker default name configuration.

io.zeebe.spring.client.annotation.ZeebeWorker declares this:

```
String name() default "${zeebe.worker.name}";
```

But ZeebeClientConfigurationProperties declares this:

```
zeebe:
  client:
    worker:
      name: 
```

Thanks for your great work

**Comment by vvalencia-cl** [comment]
The version tested is 0.4.0, with Spring Boot 2.0.3 and Java 11

**Comment by menski** [comment]
Hi @vvalencia-cl,

thanks for reporting this issue. It seems the problem is that the configuration is ignored and instead a default Zeebe client is build
https://github.com/zeebe-io/spring-zeebe/blob/a00daa9e62bccfc796419b0ed59401afd345ee63/client/spring-zeebe/src/main/java/io/zeebe/spring/client/config/ZeebeClientSpringConfiguration.java#L31-L33
https://github.com/zeebe-io/spring-zeebe/blob/a00daa9e62bccfc796419b0ed59401afd345ee63/client/spring-zeebe-starter/src/main/java/io/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java#L21-L25

@jangalinski can you confirm that this not intended behavior of these classes?

Cheers,
Sebastian

**Comment by jangalinski** [comment]
Yes, obviously a bug.
